services:
  postgres:
    image: postgres:16
    container_name: vercel_store_clone_db
    environment:
      POSTGRES_USER: clone
      POSTGRES_PASSWORD: clonepass
      POSTGRES_DB: demo_clone
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped
